config/routes.rb
Rails.application.routes.draw do
  resources :words

  get 'words/index'
  get 'words/show'
  get 'words/destroy'

  root 'home#index'

end

app/models/deleted_word.rb
class DeletedWord < ActiveRecord::Base
  belongs_to :sort
end

app/models/sort.rb
class Sort < ActiveRecord::Base
  has_many :words
  has_many :deleted_words
  
  class << self

    def get_inclusive_sorts(user_input)
      user_input = self.validate_user_input(user_input.chomp.downcase)     

      current_strings = user_input[:valid_user_input].sort
      letters = current_strings.dup
      records = current_strings.map{|sort| self.find_by(sort:sort)} - [nil]
      
      1.upto(letters.length) do
        current_strings = add_each_letter_to_each_string(current_strings,  letters)        
        records << current_strings.map{|sort| self.find_by(sort:sort)} - [nil]
      end

      records.flatten
    end

    def validate_user_input(user_input, valid_user_input_characters = [], invalid_user_input_characters = [])
      user_input_characters = user_input.chomp.downcase.split('')
      { valid_user_input:user_input_characters.select{|character| character[/[a-z]+/]}, 
        invalid_user_input:user_input_characters - user_input_characters.select{|character| character[/[a-z]+/]} }
    end

    def add_each_letter_to_each_string(strings, letters,  new_strings = [])
      new_strings = strings.map{|string| self.add_letter_to_each_string(string, letters)}
      new_strings.flatten!.uniq
    end

    def add_letter_to_each_string(string, letters)
      self.adjust_letters(letters.dup, string.dup.split('')).map{|letter| "#{string}#{letter}"}
    end

    def adjust_letters(letters, string_letters)
      while string_letters.length > 0
        string_letters.shift if string_letters[0] == letters.shift
      end
      letters
    end

  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :sort
  class << self

    def get_words_from_inclusive_sort(scrambled_word_query, word_records)
      Sort.get_inclusive_sorts(scrambled_word_query).map{|sort_record| sort_record.words}.flatten
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = params[:query] ? Word.get_words_from_inclusive_sort(params[:query], []).sort :  Word.first(50)
  end

  def show
  end

  def destroy
  end

  def search_params
    params.permit(:query)
    params.require(:word).permit(:sort_id, :length_id, :first_letter_id, :last_letter_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/word_helper.rb
module WordHelper
end

app/views/home/index.html.erb
<h1>Find the words that match your letters:</h1>

<%= render partial: "words/unscrambler_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nerdwords</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_search.html.erb
<%=form_tag words_path, method: :get do %>

  <label for="query">Enter your letters</label>
  <input type="search" name="query" id="query">
  <input type="submit" value="Search words">

<% end %> 

app/views/words/_unscrambler_form.html.erb
<%=form_tag words_path, method: :get do %>

  <label for="query">Enter your scrambled letters</label>
  <input type="search" name="query" id="query">
  <input type="submit" value="Search words">

<% end %> 

app/views/words/destroy.html.erb
<h1>Word#destroy</h1>
<p>Find me in app/views/word/destroy.html.erb</p>

app/views/words/index.html.erb
<%= render partial: "words/unscrambler_form" %>
<h1>Words</h1>

<p>
    <% @words.each do |w| %>
      <%= w.word %>
    <% end %>
</p>

app/views/words/show.html.erb
<h1>Word#show</h1>
<p>Find me in app/views/word/show.html.erb</p>